<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Orders_model extends CI_Model
{

    public $table = 'orders';
    public $id = 'order_id';
    public $order = 'DESC';

    function __construct()
    {
        //parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    function get_order_details($id)
    {
//        $this->db->where($this->id, $id);
//        return $this->db->get($this->table)->row();
        
        $this->db->select('*');
        $this->db->from($this->table);
        $this->db->join('customers', 'customers.customer_id = orders.customer_id AND orders.customer_id = '.$id);
        return $this->db->get()->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('order_id', $q);
	$this->db->or_like('customer_id', $q);
	$this->db->or_like('price', $q);
	$this->db->or_like('advance', $q);
	$this->db->or_like('delivary_date', $q);
	$this->db->or_like('date_time', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('order_id', $q);
	$this->db->or_like('customer_id', $q);
	$this->db->or_like('price', $q);
	$this->db->or_like('advance', $q);
	$this->db->or_like('delivary_date', $q);
	$this->db->or_like('date_time', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Orders_model.php */
/* Location: ./application/models/Orders_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-03-04 11:54:07 */
/* http://harviacode.com */